# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pvtransformation.ui'
#
# Created: Wed Jul 18 15:08:14 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_pvtransformationeditor(object):
    def setupUi(self, container):
        container.setObjectName(_fromUtf8("container"))
        self.gridlayout = QtGui.QGridLayout(container)
        self.gridlayout.setMargin(6)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.label_7 = QtGui.QLabel(container)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridlayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.TranslateX = QtGui.QLineEdit(container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TranslateX.sizePolicy().hasHeightForWidth())
        self.TranslateX.setSizePolicy(sizePolicy)
        self.TranslateX.setObjectName(_fromUtf8("TranslateX"))
        self.gridlayout.addWidget(self.TranslateX, 0, 1, 1, 1)
        self.TranslateY = QtGui.QLineEdit(container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TranslateY.sizePolicy().hasHeightForWidth())
        self.TranslateY.setSizePolicy(sizePolicy)
        self.TranslateY.setObjectName(_fromUtf8("TranslateY"))
        self.gridlayout.addWidget(self.TranslateY, 0, 2, 1, 1)
        self.TranslateZ = QtGui.QLineEdit(container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TranslateZ.sizePolicy().hasHeightForWidth())
        self.TranslateZ.setSizePolicy(sizePolicy)
        self.TranslateZ.setObjectName(_fromUtf8("TranslateZ"))
        self.gridlayout.addWidget(self.TranslateZ, 0, 3, 1, 1)
        self.label_8 = QtGui.QLabel(container)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridlayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.ScaleX = QtGui.QLineEdit(container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScaleX.sizePolicy().hasHeightForWidth())
        self.ScaleX.setSizePolicy(sizePolicy)
        self.ScaleX.setObjectName(_fromUtf8("ScaleX"))
        self.gridlayout.addWidget(self.ScaleX, 1, 1, 1, 1)
        self.ScaleY = QtGui.QLineEdit(container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScaleY.sizePolicy().hasHeightForWidth())
        self.ScaleY.setSizePolicy(sizePolicy)
        self.ScaleY.setObjectName(_fromUtf8("ScaleY"))
        self.gridlayout.addWidget(self.ScaleY, 1, 2, 1, 1)
        self.ScaleZ = QtGui.QLineEdit(container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScaleZ.sizePolicy().hasHeightForWidth())
        self.ScaleZ.setSizePolicy(sizePolicy)
        self.ScaleZ.setObjectName(_fromUtf8("ScaleZ"))
        self.gridlayout.addWidget(self.ScaleZ, 1, 3, 1, 1)
        self.label_9 = QtGui.QLabel(container)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridlayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.OrientationX = QtGui.QLineEdit(container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OrientationX.sizePolicy().hasHeightForWidth())
        self.OrientationX.setSizePolicy(sizePolicy)
        self.OrientationX.setObjectName(_fromUtf8("OrientationX"))
        self.gridlayout.addWidget(self.OrientationX, 2, 1, 1, 1)
        self.OrientationY = QtGui.QLineEdit(container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OrientationY.sizePolicy().hasHeightForWidth())
        self.OrientationY.setSizePolicy(sizePolicy)
        self.OrientationY.setObjectName(_fromUtf8("OrientationY"))
        self.gridlayout.addWidget(self.OrientationY, 2, 2, 1, 1)
        self.OrientationZ = QtGui.QLineEdit(container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OrientationZ.sizePolicy().hasHeightForWidth())
        self.OrientationZ.setSizePolicy(sizePolicy)
        self.OrientationZ.setObjectName(_fromUtf8("OrientationZ"))
        self.gridlayout.addWidget(self.OrientationZ, 2, 3, 1, 1)
        self.label_10 = QtGui.QLabel(container)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridlayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.OriginX = QtGui.QLineEdit(container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OriginX.sizePolicy().hasHeightForWidth())
        self.OriginX.setSizePolicy(sizePolicy)
        self.OriginX.setObjectName(_fromUtf8("OriginX"))
        self.gridlayout.addWidget(self.OriginX, 3, 1, 1, 1)
        self.OriginY = QtGui.QLineEdit(container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OriginY.sizePolicy().hasHeightForWidth())
        self.OriginY.setSizePolicy(sizePolicy)
        self.OriginY.setObjectName(_fromUtf8("OriginY"))
        self.gridlayout.addWidget(self.OriginY, 3, 2, 1, 1)
        self.OriginZ = QtGui.QLineEdit(container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OriginZ.sizePolicy().hasHeightForWidth())
        self.OriginZ.setSizePolicy(sizePolicy)
        self.OriginZ.setObjectName(_fromUtf8("OriginZ"))
        self.gridlayout.addWidget(self.OriginZ, 3, 3, 1, 1)

        self.retranslateUi(container)

    def retranslateUi(self, container):
        self.label_7.setText(QtGui.QApplication.translate("pvtransformationeditor", "Translate", None, QtGui.QApplication.UnicodeUTF8))
        self.TranslateX.setToolTip(QtGui.QApplication.translate("pvtransformationeditor", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Translate the geometry relative to the dataset location.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.TranslateY.setToolTip(QtGui.QApplication.translate("pvtransformationeditor", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Translate the geometry relative to the dataset location.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.TranslateZ.setToolTip(QtGui.QApplication.translate("pvtransformationeditor", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Translate the geometry relative to the dataset location.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("pvtransformationeditor", "Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.ScaleX.setToolTip(QtGui.QApplication.translate("pvtransformationeditor", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Scale the geometry relative to the size of the dataset.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.ScaleY.setToolTip(QtGui.QApplication.translate("pvtransformationeditor", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Scale the geometry relative to the size of the dataset.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.ScaleZ.setToolTip(QtGui.QApplication.translate("pvtransformationeditor", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Scale the geometry relative to the size of the dataset.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("pvtransformationeditor", "Orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.OrientationX.setToolTip(QtGui.QApplication.translate("pvtransformationeditor", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Orient the geometry relative to the dataset origin.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.OrientationY.setToolTip(QtGui.QApplication.translate("pvtransformationeditor", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Orient the geometry relative to the dataset origin.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.OrientationZ.setToolTip(QtGui.QApplication.translate("pvtransformationeditor", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Orient the geometry relative to the dataset origin.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("pvtransformationeditor", "Origin", None, QtGui.QApplication.UnicodeUTF8))
        self.OriginX.setToolTip(QtGui.QApplication.translate("pvtransformationeditor", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Set the origin point about which rotations take place.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.OriginY.setToolTip(QtGui.QApplication.translate("pvtransformationeditor", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Set the origin point about which rotations take place.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.OriginZ.setToolTip(QtGui.QApplication.translate("pvtransformationeditor", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Set the origin point about which rotations take place.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

