############################################################################
##
## Copyright (C) 2006-2010 University of Utah. All rights reserved.
##
## This file is part of VisTrails.
##
## This file may be used under the terms of the GNU General Public
## License version 2.0 as published by the Free Software Foundation
## and appearing in the file LICENSE.GPL included in the packaging of
## this file.  Please review the following to ensure GNU General Public
## Licensing requirements will be met:
## http://www.opensource.org/licenses/gpl-license.php
##
## If you are unsure which license is appropriate for your use (for
## instance, you are interested in developing a commercial derivative
## of VisTrails), please contact us at vistrails@sci.utah.edu.
##
## This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
## WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
##
############################################################################
""" Do not edit this file!

File automatically generated by scripts/gen_init.py
Change History:
version : description
  0.2   : Integrated quickplot module that displays the CDAT plot
          widget inside the spreadsheet  
  0.1   : First automatically generated package based on xml descriptions

"""


version = "0.2"
identifier = "edu.utah.sci.vistrails.cdat"
name = "CDAT"



def package_dependencies():
    return ['edu.utah.sci.vistrails.spreadsheet',
            'edu.utah.sci.vistrails.vtk',
            'edu.utah.sci.eranders.ParaView']


def package_requirements():
    import core.requirements
    if not core.requirements.python_module_exists('vcs'):
        raise core.requirements.MissingRequirements('vcs')
    if not core.requirements.python_module_exists('cdms2'):
        raise core.requirements.MissingRequirements('cdms2')
    if not core.requirements.python_module_exists('cdutil'):
        raise core.requirements.MissingRequirements('cdutil')
    if not core.requirements.python_module_exists('lepl'):
        raise core.requirements.MissingRequirements('lepl')
    import vcs, cdms2, cdutil, lepl

