# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diagnosticsDockWidget.ui'
#
# Created: Wed Mar 26 10:23:28 2014
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DiagnosticDockWidget(object):
    def setupUi(self, DiagnosticDockWidget):
        DiagnosticDockWidget.setObjectName(_fromUtf8("DiagnosticDockWidget"))
        DiagnosticDockWidget.resize(450, 473)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.layoutWidget = QtGui.QWidget(self.dockWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 421, 431))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.mainLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.mainLayout.setMargin(0)
        self.mainLayout.setObjectName(_fromUtf8("mainLayout"))
        self.scrollArea = QtGui.QScrollArea(self.layoutWidget)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 392, 781))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.diagsGroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.diagsGroupBox.setCheckable(False)
        self.diagsGroupBox.setObjectName(_fromUtf8("diagsGroupBox"))
        self.diagGridLayout = QtGui.QGridLayout(self.diagsGroupBox)
        self.diagGridLayout.setObjectName(_fromUtf8("diagGridLayout"))
        self.treeWidget = QtGui.QTreeWidget(self.diagsGroupBox)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.treeWidget.header().setVisible(False)
        self.diagGridLayout.addWidget(self.treeWidget, 1, 0, 1, 3)
        self.PackageLabel = QtGui.QLabel(self.diagsGroupBox)
        self.PackageLabel.setObjectName(_fromUtf8("PackageLabel"))
        self.diagGridLayout.addWidget(self.PackageLabel, 0, 0, 1, 1)
        self.comboBoxType = QtGui.QComboBox(self.diagsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxType.sizePolicy().hasHeightForWidth())
        self.comboBoxType.setSizePolicy(sizePolicy)
        self.comboBoxType.setObjectName(_fromUtf8("comboBoxType"))
        self.diagGridLayout.addWidget(self.comboBoxType, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.diagsGroupBox)
        self.variablesGroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.variablesGroupBox.setObjectName(_fromUtf8("variablesGroupBox"))
        self.varGridLayout = QtGui.QGridLayout(self.variablesGroupBox)
        self.varGridLayout.setObjectName(_fromUtf8("varGridLayout"))
        self.comboBoxAux = QtGui.QComboBox(self.variablesGroupBox)
        self.comboBoxAux.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxAux.sizePolicy().hasHeightForWidth())
        self.comboBoxAux.setSizePolicy(sizePolicy)
        self.comboBoxAux.setObjectName(_fromUtf8("comboBoxAux"))
        self.varGridLayout.addWidget(self.comboBoxAux, 0, 2, 1, 1)
        self.VarOptionsLabel = QtGui.QLabel(self.variablesGroupBox)
        self.VarOptionsLabel.setObjectName(_fromUtf8("VarOptionsLabel"))
        self.varGridLayout.addWidget(self.VarOptionsLabel, 0, 1, 1, 1)
        self.comboBoxVar = QtGui.QComboBox(self.variablesGroupBox)
        self.comboBoxVar.setEnabled(False)
        self.comboBoxVar.setObjectName(_fromUtf8("comboBoxVar"))
        self.varGridLayout.addWidget(self.comboBoxVar, 0, 0, 1, 1)
        self.comboBoxSeason = QtGui.QComboBox(self.variablesGroupBox)
        self.comboBoxSeason.setEnabled(False)
        self.comboBoxSeason.setObjectName(_fromUtf8("comboBoxSeason"))
        self.varGridLayout.addWidget(self.comboBoxSeason, 1, 0, 1, 1)
        self.RegionLabel = QtGui.QLabel(self.variablesGroupBox)
        self.RegionLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RegionLabel.setObjectName(_fromUtf8("RegionLabel"))
        self.varGridLayout.addWidget(self.RegionLabel, 1, 1, 1, 1)
        self.comboBoxRegion = QtGui.QComboBox(self.variablesGroupBox)
        self.comboBoxRegion.setEnabled(False)
        self.comboBoxRegion.setObjectName(_fromUtf8("comboBoxRegion"))
        self.varGridLayout.addWidget(self.comboBoxRegion, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.variablesGroupBox)
        self.DS1GroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.DS1GroupBox.setCheckable(True)
        self.DS1GroupBox.setObjectName(_fromUtf8("DS1GroupBox"))
        self.DS1GridLayout = QtGui.QGridLayout(self.DS1GroupBox)
        self.DS1GridLayout.setObjectName(_fromUtf8("DS1GridLayout"))
        self.pickDS1Path = QtGui.QPushButton(self.DS1GroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickDS1Path.sizePolicy().hasHeightForWidth())
        self.pickDS1Path.setSizePolicy(sizePolicy)
        self.pickDS1Path.setObjectName(_fromUtf8("pickDS1Path"))
        self.DS1GridLayout.addWidget(self.pickDS1Path, 0, 0, 1, 1)
        self.DS1ShortnameEdit = QtGui.QLineEdit(self.DS1GroupBox)
        self.DS1ShortnameEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DS1ShortnameEdit.sizePolicy().hasHeightForWidth())
        self.DS1ShortnameEdit.setSizePolicy(sizePolicy)
        self.DS1ShortnameEdit.setObjectName(_fromUtf8("DS1ShortnameEdit"))
        self.DS1GridLayout.addWidget(self.DS1ShortnameEdit, 1, 0, 1, 1)
        self.DS1FilterLabel = QtGui.QLabel(self.DS1GroupBox)
        self.DS1FilterLabel.setMinimumSize(QtCore.QSize(93, 0))
        self.DS1FilterLabel.setObjectName(_fromUtf8("DS1FilterLabel"))
        self.DS1GridLayout.addWidget(self.DS1FilterLabel, 1, 1, 1, 1)
        self.DS1FilterEdit = QtGui.QLineEdit(self.DS1GroupBox)
        self.DS1FilterEdit.setObjectName(_fromUtf8("DS1FilterEdit"))
        self.DS1GridLayout.addWidget(self.DS1FilterEdit, 1, 2, 1, 1)
        self.DS1PathLabel = QtGui.QLabel(self.DS1GroupBox)
        self.DS1PathLabel.setObjectName(_fromUtf8("DS1PathLabel"))
        self.DS1GridLayout.addWidget(self.DS1PathLabel, 0, 1, 1, 2)
        self.DS1TimeGrid = QtGui.QGridLayout()
        self.DS1TimeGrid.setObjectName(_fromUtf8("DS1TimeGrid"))
        self.DS1TimeRangeCheck = QtGui.QCheckBox(self.DS1GroupBox)
        self.DS1TimeRangeCheck.setEnabled(True)
        self.DS1TimeRangeCheck.setObjectName(_fromUtf8("DS1TimeRangeCheck"))
        self.DS1TimeGrid.addWidget(self.DS1TimeRangeCheck, 0, 0, 1, 1)
        self.StartYear1HBox = QtGui.QHBoxLayout()
        self.StartYear1HBox.setObjectName(_fromUtf8("StartYear1HBox"))
        self.DS1StartLabel = QtGui.QLabel(self.DS1GroupBox)
        self.DS1StartLabel.setEnabled(False)
        self.DS1StartLabel.setObjectName(_fromUtf8("DS1StartLabel"))
        self.StartYear1HBox.addWidget(self.DS1StartLabel)
        self.DS1StartEdit = QtGui.QLineEdit(self.DS1GroupBox)
        self.DS1StartEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DS1StartEdit.sizePolicy().hasHeightForWidth())
        self.DS1StartEdit.setSizePolicy(sizePolicy)
        self.DS1StartEdit.setObjectName(_fromUtf8("DS1StartEdit"))
        self.StartYear1HBox.addWidget(self.DS1StartEdit)
        self.DS1TimeGrid.addLayout(self.StartYear1HBox, 0, 1, 1, 1)
        self.EndYear1HBox = QtGui.QHBoxLayout()
        self.EndYear1HBox.setObjectName(_fromUtf8("EndYear1HBox"))
        self.DS1EndLabel = QtGui.QLabel(self.DS1GroupBox)
        self.DS1EndLabel.setEnabled(False)
        self.DS1EndLabel.setObjectName(_fromUtf8("DS1EndLabel"))
        self.EndYear1HBox.addWidget(self.DS1EndLabel)
        self.DS1EndEdit = QtGui.QLineEdit(self.DS1GroupBox)
        self.DS1EndEdit.setEnabled(False)
        self.DS1EndEdit.setText(_fromUtf8(""))
        self.DS1EndEdit.setObjectName(_fromUtf8("DS1EndEdit"))
        self.EndYear1HBox.addWidget(self.DS1EndEdit)
        self.DS1TimeGrid.addLayout(self.EndYear1HBox, 0, 2, 1, 1)
        self.DS1GridLayout.addLayout(self.DS1TimeGrid, 2, 0, 1, 3)
        self.verticalLayout_2.addWidget(self.DS1GroupBox)
        self.DS2GroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.DS2GroupBox.setCheckable(True)
        self.DS2GroupBox.setChecked(False)
        self.DS2GroupBox.setObjectName(_fromUtf8("DS2GroupBox"))
        self.DS2GridLayout = QtGui.QGridLayout(self.DS2GroupBox)
        self.DS2GridLayout.setObjectName(_fromUtf8("DS2GridLayout"))
        self.pickDS2Path = QtGui.QPushButton(self.DS2GroupBox)
        self.pickDS2Path.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickDS2Path.sizePolicy().hasHeightForWidth())
        self.pickDS2Path.setSizePolicy(sizePolicy)
        self.pickDS2Path.setObjectName(_fromUtf8("pickDS2Path"))
        self.DS2GridLayout.addWidget(self.pickDS2Path, 0, 0, 1, 1)
        self.DS2PathLabel = QtGui.QLabel(self.DS2GroupBox)
        self.DS2PathLabel.setObjectName(_fromUtf8("DS2PathLabel"))
        self.DS2GridLayout.addWidget(self.DS2PathLabel, 0, 1, 1, 2)
        self.DS2FilterLabel = QtGui.QLabel(self.DS2GroupBox)
        self.DS2FilterLabel.setMinimumSize(QtCore.QSize(93, 0))
        self.DS2FilterLabel.setObjectName(_fromUtf8("DS2FilterLabel"))
        self.DS2GridLayout.addWidget(self.DS2FilterLabel, 2, 1, 1, 1)
        self.DS2TimeGrid = QtGui.QGridLayout()
        self.DS2TimeGrid.setObjectName(_fromUtf8("DS2TimeGrid"))
        self.DS2TimeRangeCheck = QtGui.QCheckBox(self.DS2GroupBox)
        self.DS2TimeRangeCheck.setEnabled(False)
        self.DS2TimeRangeCheck.setObjectName(_fromUtf8("DS2TimeRangeCheck"))
        self.DS2TimeGrid.addWidget(self.DS2TimeRangeCheck, 0, 0, 1, 1)
        self.StartYear2HBox = QtGui.QHBoxLayout()
        self.StartYear2HBox.setObjectName(_fromUtf8("StartYear2HBox"))
        self.DS2StartLabel = QtGui.QLabel(self.DS2GroupBox)
        self.DS2StartLabel.setEnabled(False)
        self.DS2StartLabel.setObjectName(_fromUtf8("DS2StartLabel"))
        self.StartYear2HBox.addWidget(self.DS2StartLabel)
        self.DS2StartEdit = QtGui.QLineEdit(self.DS2GroupBox)
        self.DS2StartEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DS2StartEdit.sizePolicy().hasHeightForWidth())
        self.DS2StartEdit.setSizePolicy(sizePolicy)
        self.DS2StartEdit.setObjectName(_fromUtf8("DS2StartEdit"))
        self.StartYear2HBox.addWidget(self.DS2StartEdit)
        self.DS2TimeGrid.addLayout(self.StartYear2HBox, 0, 1, 1, 1)
        self.EndYear2HBox = QtGui.QHBoxLayout()
        self.EndYear2HBox.setObjectName(_fromUtf8("EndYear2HBox"))
        self.DS2EndLabel = QtGui.QLabel(self.DS2GroupBox)
        self.DS2EndLabel.setEnabled(False)
        self.DS2EndLabel.setObjectName(_fromUtf8("DS2EndLabel"))
        self.EndYear2HBox.addWidget(self.DS2EndLabel)
        self.DS2EndEdit = QtGui.QLineEdit(self.DS2GroupBox)
        self.DS2EndEdit.setEnabled(False)
        self.DS2EndEdit.setText(_fromUtf8(""))
        self.DS2EndEdit.setObjectName(_fromUtf8("DS2EndEdit"))
        self.EndYear2HBox.addWidget(self.DS2EndEdit)
        self.DS2TimeGrid.addLayout(self.EndYear2HBox, 0, 2, 1, 1)
        self.DS2GridLayout.addLayout(self.DS2TimeGrid, 4, 0, 1, 3)
        self.DS2ShortnameEdit = QtGui.QLineEdit(self.DS2GroupBox)
        self.DS2ShortnameEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DS2ShortnameEdit.sizePolicy().hasHeightForWidth())
        self.DS2ShortnameEdit.setSizePolicy(sizePolicy)
        self.DS2ShortnameEdit.setObjectName(_fromUtf8("DS2ShortnameEdit"))
        self.DS2GridLayout.addWidget(self.DS2ShortnameEdit, 2, 0, 1, 1)
        self.DS2FilterEdit = QtGui.QLineEdit(self.DS2GroupBox)
        self.DS2FilterEdit.setEnabled(False)
        self.DS2FilterEdit.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.DS2FilterEdit.setObjectName(_fromUtf8("DS2FilterEdit"))
        self.DS2GridLayout.addWidget(self.DS2FilterEdit, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.DS2GroupBox)
        self.obs1GroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.obs1GroupBox.setCheckable(True)
        self.obs1GroupBox.setChecked(False)
        self.obs1GroupBox.setObjectName(_fromUtf8("obs1GroupBox"))
        self.Obs1GridLayout = QtGui.QGridLayout(self.obs1GroupBox)
        self.Obs1GridLayout.setObjectName(_fromUtf8("Obs1GridLayout"))
        self.pickObs1Path = QtGui.QPushButton(self.obs1GroupBox)
        self.pickObs1Path.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickObs1Path.sizePolicy().hasHeightForWidth())
        self.pickObs1Path.setSizePolicy(sizePolicy)
        self.pickObs1Path.setObjectName(_fromUtf8("pickObs1Path"))
        self.Obs1GridLayout.addWidget(self.pickObs1Path, 0, 0, 1, 1)
        self.obs1PathLabel = QtGui.QLabel(self.obs1GroupBox)
        self.obs1PathLabel.setEnabled(False)
        self.obs1PathLabel.setObjectName(_fromUtf8("obs1PathLabel"))
        self.Obs1GridLayout.addWidget(self.obs1PathLabel, 0, 1, 1, 2)
        self.obs1TranslateCheck = QtGui.QCheckBox(self.obs1GroupBox)
        self.obs1TranslateCheck.setEnabled(False)
        self.obs1TranslateCheck.setObjectName(_fromUtf8("obs1TranslateCheck"))
        self.Obs1GridLayout.addWidget(self.obs1TranslateCheck, 1, 0, 1, 1)
        self.comboBoxObservation1 = QtGui.QComboBox(self.obs1GroupBox)
        self.comboBoxObservation1.setEnabled(False)
        self.comboBoxObservation1.setObjectName(_fromUtf8("comboBoxObservation1"))
        self.Obs1GridLayout.addWidget(self.comboBoxObservation1, 1, 2, 1, 1)
        self.Obs1Label = QtGui.QLabel(self.obs1GroupBox)
        self.Obs1Label.setObjectName(_fromUtf8("Obs1Label"))
        self.Obs1GridLayout.addWidget(self.Obs1Label, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.obs1GroupBox)
        self.obs2GroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.obs2GroupBox.setEnabled(True)
        self.obs2GroupBox.setCheckable(True)
        self.obs2GroupBox.setChecked(False)
        self.obs2GroupBox.setObjectName(_fromUtf8("obs2GroupBox"))
        self.Obs2GridLayout = QtGui.QGridLayout(self.obs2GroupBox)
        self.Obs2GridLayout.setObjectName(_fromUtf8("Obs2GridLayout"))
        self.pickObs2Path = QtGui.QPushButton(self.obs2GroupBox)
        self.pickObs2Path.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickObs2Path.sizePolicy().hasHeightForWidth())
        self.pickObs2Path.setSizePolicy(sizePolicy)
        self.pickObs2Path.setObjectName(_fromUtf8("pickObs2Path"))
        self.Obs2GridLayout.addWidget(self.pickObs2Path, 0, 0, 1, 1)
        self.obs2TranslateCheck = QtGui.QCheckBox(self.obs2GroupBox)
        self.obs2TranslateCheck.setEnabled(False)
        self.obs2TranslateCheck.setObjectName(_fromUtf8("obs2TranslateCheck"))
        self.Obs2GridLayout.addWidget(self.obs2TranslateCheck, 1, 0, 1, 1)
        self.obs2PathLabel = QtGui.QLabel(self.obs2GroupBox)
        self.obs2PathLabel.setEnabled(False)
        self.obs2PathLabel.setObjectName(_fromUtf8("obs2PathLabel"))
        self.Obs2GridLayout.addWidget(self.obs2PathLabel, 0, 1, 1, 2)
        self.comboBoxObservation2 = QtGui.QComboBox(self.obs2GroupBox)
        self.comboBoxObservation2.setEnabled(False)
        self.comboBoxObservation2.setObjectName(_fromUtf8("comboBoxObservation2"))
        self.Obs2GridLayout.addWidget(self.comboBoxObservation2, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.obs2GroupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.Obs2GridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.obs2GroupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.mainLayout.addWidget(self.scrollArea)
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.mainLayout.addWidget(self.buttonBox)
        DiagnosticDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DiagnosticDockWidget)
        QtCore.QMetaObject.connectSlotsByName(DiagnosticDockWidget)

    def retranslateUi(self, DiagnosticDockWidget):
        DiagnosticDockWidget.setWindowTitle(_translate("DiagnosticDockWidget", "Diagnostics", None))
        self.diagsGroupBox.setTitle(_translate("DiagnosticDockWidget", "Diagnostics", None))
        self.PackageLabel.setText(_translate("DiagnosticDockWidget", "Package:", None))
        self.variablesGroupBox.setTitle(_translate("DiagnosticDockWidget", "Variable", None))
        self.VarOptionsLabel.setText(_translate("DiagnosticDockWidget", "Variable Options:", None))
        self.RegionLabel.setText(_translate("DiagnosticDockWidget", "Region:", None))
        self.DS1GroupBox.setTitle(_translate("DiagnosticDockWidget", "Dataset 1", None))
        self.pickDS1Path.setText(_translate("DiagnosticDockWidget", "Set Path", None))
        self.DS1ShortnameEdit.setText(_translate("DiagnosticDockWidget", "Opt DS Name", None))
        self.DS1FilterLabel.setText(_translate("DiagnosticDockWidget", "File Filter:", None))
        self.DS1PathLabel.setText(_translate("DiagnosticDockWidget", "DS1 Path", None))
        self.DS1TimeRangeCheck.setText(_translate("DiagnosticDockWidget", "Specify Time Range:", None))
        self.DS1StartLabel.setText(_translate("DiagnosticDockWidget", "Start:", None))
        self.DS1EndLabel.setText(_translate("DiagnosticDockWidget", "End:", None))
        self.DS2GroupBox.setTitle(_translate("DiagnosticDockWidget", "Dataset 2", None))
        self.pickDS2Path.setText(_translate("DiagnosticDockWidget", "Set Path", None))
        self.DS2PathLabel.setText(_translate("DiagnosticDockWidget", "DS2 Path", None))
        self.DS2FilterLabel.setText(_translate("DiagnosticDockWidget", "File Filter:", None))
        self.DS2TimeRangeCheck.setText(_translate("DiagnosticDockWidget", "Specify Time Range:", None))
        self.DS2StartLabel.setText(_translate("DiagnosticDockWidget", "Start:", None))
        self.DS2EndLabel.setText(_translate("DiagnosticDockWidget", "End:", None))
        self.DS2ShortnameEdit.setText(_translate("DiagnosticDockWidget", "Optional Shortname", None))
        self.obs1GroupBox.setTitle(_translate("DiagnosticDockWidget", "Observations 1", None))
        self.pickObs1Path.setText(_translate("DiagnosticDockWidget", "Set Path", None))
        self.obs1PathLabel.setText(_translate("DiagnosticDockWidget", "ObsPath1", None))
        self.obs1TranslateCheck.setText(_translate("DiagnosticDockWidget", "Translate Var Names", None))
        self.Obs1Label.setText(_translate("DiagnosticDockWidget", "Obs set:", None))
        self.obs2GroupBox.setTitle(_translate("DiagnosticDockWidget", "Observations 2", None))
        self.pickObs2Path.setText(_translate("DiagnosticDockWidget", "Set Path", None))
        self.obs2TranslateCheck.setText(_translate("DiagnosticDockWidget", "Translate Var Names", None))
        self.obs2PathLabel.setText(_translate("DiagnosticDockWidget", "ObsPath2", None))
        self.label.setText(_translate("DiagnosticDockWidget", "Obs set:", None))

