# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diagnosticsDockWidget.ui'
#
# Created: Wed Jul  9 10:15:34 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DiagnosticDockWidget(object):
    def setupUi(self, DiagnosticDockWidget):
        DiagnosticDockWidget.setObjectName(_fromUtf8("DiagnosticDockWidget"))
        DiagnosticDockWidget.resize(604, 899)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 563, 817))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.diagsGroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.diagsGroupBox.setCheckable(False)
        self.diagsGroupBox.setObjectName(_fromUtf8("diagsGroupBox"))
        self.diagGridLayout = QtGui.QGridLayout(self.diagsGroupBox)
        self.diagGridLayout.setObjectName(_fromUtf8("diagGridLayout"))
        self.treeWidget = QtGui.QTreeWidget(self.diagsGroupBox)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.treeWidget.header().setVisible(False)
        self.diagGridLayout.addWidget(self.treeWidget, 1, 0, 1, 3)
        self.PackageLabel = QtGui.QLabel(self.diagsGroupBox)
        self.PackageLabel.setObjectName(_fromUtf8("PackageLabel"))
        self.diagGridLayout.addWidget(self.PackageLabel, 0, 0, 1, 1)
        self.comboBoxType = QtGui.QComboBox(self.diagsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxType.sizePolicy().hasHeightForWidth())
        self.comboBoxType.setSizePolicy(sizePolicy)
        self.comboBoxType.setObjectName(_fromUtf8("comboBoxType"))
        self.diagGridLayout.addWidget(self.comboBoxType, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.diagsGroupBox)
        self.variablesGroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.variablesGroupBox.setObjectName(_fromUtf8("variablesGroupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.variablesGroupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.VarOptionsLabel_2 = QtGui.QLabel(self.variablesGroupBox)
        self.VarOptionsLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.VarOptionsLabel_2.setObjectName(_fromUtf8("VarOptionsLabel_2"))
        self.gridLayout_4.addWidget(self.VarOptionsLabel_2, 0, 0, 1, 1)
        self.comboBoxVar = QtGui.QComboBox(self.variablesGroupBox)
        self.comboBoxVar.setEnabled(False)
        self.comboBoxVar.setObjectName(_fromUtf8("comboBoxVar"))
        self.gridLayout_4.addWidget(self.comboBoxVar, 0, 1, 1, 1)
        self.RegionLabel_2 = QtGui.QLabel(self.variablesGroupBox)
        self.RegionLabel_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RegionLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.RegionLabel_2.setObjectName(_fromUtf8("RegionLabel_2"))
        self.gridLayout_4.addWidget(self.RegionLabel_2, 1, 0, 1, 1)
        self.comboBoxSeason = QtGui.QComboBox(self.variablesGroupBox)
        self.comboBoxSeason.setEnabled(False)
        self.comboBoxSeason.setObjectName(_fromUtf8("comboBoxSeason"))
        self.gridLayout_4.addWidget(self.comboBoxSeason, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.VarOptionsLabel = QtGui.QLabel(self.variablesGroupBox)
        self.VarOptionsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.VarOptionsLabel.setObjectName(_fromUtf8("VarOptionsLabel"))
        self.gridLayout_5.addWidget(self.VarOptionsLabel, 0, 0, 1, 1)
        self.comboBoxAux = QtGui.QComboBox(self.variablesGroupBox)
        self.comboBoxAux.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxAux.sizePolicy().hasHeightForWidth())
        self.comboBoxAux.setSizePolicy(sizePolicy)
        self.comboBoxAux.setObjectName(_fromUtf8("comboBoxAux"))
        self.gridLayout_5.addWidget(self.comboBoxAux, 0, 1, 1, 1)
        self.RegionLabel = QtGui.QLabel(self.variablesGroupBox)
        self.RegionLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RegionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.RegionLabel.setObjectName(_fromUtf8("RegionLabel"))
        self.gridLayout_5.addWidget(self.RegionLabel, 1, 0, 1, 1)
        self.comboBoxRegion = QtGui.QComboBox(self.variablesGroupBox)
        self.comboBoxRegion.setEnabled(False)
        self.comboBoxRegion.setObjectName(_fromUtf8("comboBoxRegion"))
        self.gridLayout_5.addWidget(self.comboBoxRegion, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.variablesGroupBox)
        self.DS1checkBox = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.DS1checkBox.setChecked(True)
        self.DS1checkBox.setObjectName(_fromUtf8("DS1checkBox"))
        self.verticalLayout_2.addWidget(self.DS1checkBox)
        self.DS1GroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.DS1GroupBox.setTitle(_fromUtf8(""))
        self.DS1GroupBox.setCheckable(False)
        self.DS1GroupBox.setObjectName(_fromUtf8("DS1GroupBox"))
        self.DS1GridLayout = QtGui.QGridLayout(self.DS1GroupBox)
        self.DS1GridLayout.setObjectName(_fromUtf8("DS1GridLayout"))
        self.DS1FilterLabel = QtGui.QLabel(self.DS1GroupBox)
        self.DS1FilterLabel.setMinimumSize(QtCore.QSize(93, 0))
        self.DS1FilterLabel.setObjectName(_fromUtf8("DS1FilterLabel"))
        self.DS1GridLayout.addWidget(self.DS1FilterLabel, 2, 0, 1, 1)
        self.pickDS1Path = QtGui.QPushButton(self.DS1GroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickDS1Path.sizePolicy().hasHeightForWidth())
        self.pickDS1Path.setSizePolicy(sizePolicy)
        self.pickDS1Path.setMinimumSize(QtCore.QSize(92, 32))
        self.pickDS1Path.setObjectName(_fromUtf8("pickDS1Path"))
        self.DS1GridLayout.addWidget(self.pickDS1Path, 1, 0, 1, 1)
        self.DS1FilterEdit = QtGui.QLineEdit(self.DS1GroupBox)
        self.DS1FilterEdit.setObjectName(_fromUtf8("DS1FilterEdit"))
        self.DS1GridLayout.addWidget(self.DS1FilterEdit, 2, 1, 1, 1)
        self.DS1PathLabel = QtGui.QLabel(self.DS1GroupBox)
        self.DS1PathLabel.setEnabled(False)
        self.DS1PathLabel.setObjectName(_fromUtf8("DS1PathLabel"))
        self.DS1GridLayout.addWidget(self.DS1PathLabel, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.DS1GroupBox)
        self.DS2checkBox = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.DS2checkBox.setChecked(False)
        self.DS2checkBox.setObjectName(_fromUtf8("DS2checkBox"))
        self.verticalLayout_2.addWidget(self.DS2checkBox)
        self.DS2GroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.DS2GroupBox.setTitle(_fromUtf8(""))
        self.DS2GroupBox.setCheckable(False)
        self.DS2GroupBox.setChecked(False)
        self.DS2GroupBox.setObjectName(_fromUtf8("DS2GroupBox"))
        self.DS2GridLayout = QtGui.QGridLayout(self.DS2GroupBox)
        self.DS2GridLayout.setObjectName(_fromUtf8("DS2GridLayout"))
        self.DS2FilterEdit = QtGui.QLineEdit(self.DS2GroupBox)
        self.DS2FilterEdit.setEnabled(False)
        self.DS2FilterEdit.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.DS2FilterEdit.setObjectName(_fromUtf8("DS2FilterEdit"))
        self.DS2GridLayout.addWidget(self.DS2FilterEdit, 3, 2, 1, 1)
        self.pickDS2Path = QtGui.QPushButton(self.DS2GroupBox)
        self.pickDS2Path.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickDS2Path.sizePolicy().hasHeightForWidth())
        self.pickDS2Path.setSizePolicy(sizePolicy)
        self.pickDS2Path.setMinimumSize(QtCore.QSize(92, 32))
        self.pickDS2Path.setObjectName(_fromUtf8("pickDS2Path"))
        self.DS2GridLayout.addWidget(self.pickDS2Path, 1, 0, 1, 1)
        self.DS2FilterLabel = QtGui.QLabel(self.DS2GroupBox)
        self.DS2FilterLabel.setMinimumSize(QtCore.QSize(93, 0))
        self.DS2FilterLabel.setObjectName(_fromUtf8("DS2FilterLabel"))
        self.DS2GridLayout.addWidget(self.DS2FilterLabel, 3, 0, 1, 1)
        self.DS2PathLabel = QtGui.QLabel(self.DS2GroupBox)
        self.DS2PathLabel.setEnabled(False)
        self.DS2PathLabel.setObjectName(_fromUtf8("DS2PathLabel"))
        self.DS2GridLayout.addWidget(self.DS2PathLabel, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.DS2GroupBox)
        self.Obs1checkBox = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.Obs1checkBox.setChecked(False)
        self.Obs1checkBox.setObjectName(_fromUtf8("Obs1checkBox"))
        self.verticalLayout_2.addWidget(self.Obs1checkBox)
        self.obs1GroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.obs1GroupBox.setEnabled(True)
        self.obs1GroupBox.setMinimumSize(QtCore.QSize(0, 81))
        self.obs1GroupBox.setTitle(_fromUtf8(""))
        self.obs1GroupBox.setCheckable(False)
        self.obs1GroupBox.setChecked(False)
        self.obs1GroupBox.setObjectName(_fromUtf8("obs1GroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.obs1GroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pickObs1Path = QtGui.QPushButton(self.obs1GroupBox)
        self.pickObs1Path.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickObs1Path.sizePolicy().hasHeightForWidth())
        self.pickObs1Path.setSizePolicy(sizePolicy)
        self.pickObs1Path.setMinimumSize(QtCore.QSize(92, 32))
        self.pickObs1Path.setMaximumSize(QtCore.QSize(92, 16777215))
        self.pickObs1Path.setObjectName(_fromUtf8("pickObs1Path"))
        self.gridLayout_2.addWidget(self.pickObs1Path, 0, 0, 1, 1)
        self.obs1PathLabel = QtGui.QLabel(self.obs1GroupBox)
        self.obs1PathLabel.setEnabled(False)
        self.obs1PathLabel.setObjectName(_fromUtf8("obs1PathLabel"))
        self.gridLayout_2.addWidget(self.obs1PathLabel, 0, 1, 1, 1)
        self.Obs1Label = QtGui.QLabel(self.obs1GroupBox)
        self.Obs1Label.setObjectName(_fromUtf8("Obs1Label"))
        self.gridLayout_2.addWidget(self.Obs1Label, 1, 0, 1, 1)
        self.comboBoxObservation1 = QtGui.QComboBox(self.obs1GroupBox)
        self.comboBoxObservation1.setEnabled(False)
        self.comboBoxObservation1.setObjectName(_fromUtf8("comboBoxObservation1"))
        self.gridLayout_2.addWidget(self.comboBoxObservation1, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.obs1GroupBox)
        self.Obs2checkBox = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.Obs2checkBox.setChecked(False)
        self.Obs2checkBox.setObjectName(_fromUtf8("Obs2checkBox"))
        self.verticalLayout_2.addWidget(self.Obs2checkBox)
        self.obs2GroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.obs2GroupBox.setEnabled(True)
        self.obs2GroupBox.setMinimumSize(QtCore.QSize(0, 81))
        self.obs2GroupBox.setTitle(_fromUtf8(""))
        self.obs2GroupBox.setCheckable(False)
        self.obs2GroupBox.setChecked(False)
        self.obs2GroupBox.setObjectName(_fromUtf8("obs2GroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.obs2GroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pickObs2Path = QtGui.QPushButton(self.obs2GroupBox)
        self.pickObs2Path.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickObs2Path.sizePolicy().hasHeightForWidth())
        self.pickObs2Path.setSizePolicy(sizePolicy)
        self.pickObs2Path.setMinimumSize(QtCore.QSize(92, 32))
        self.pickObs2Path.setMaximumSize(QtCore.QSize(92, 16777215))
        self.pickObs2Path.setObjectName(_fromUtf8("pickObs2Path"))
        self.gridLayout_3.addWidget(self.pickObs2Path, 0, 0, 1, 1)
        self.obs2PathLabel = QtGui.QLabel(self.obs2GroupBox)
        self.obs2PathLabel.setEnabled(False)
        self.obs2PathLabel.setObjectName(_fromUtf8("obs2PathLabel"))
        self.gridLayout_3.addWidget(self.obs2PathLabel, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.obs2GroupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.comboBoxObservation2 = QtGui.QComboBox(self.obs2GroupBox)
        self.comboBoxObservation2.setEnabled(False)
        self.comboBoxObservation2.setObjectName(_fromUtf8("comboBoxObservation2"))
        self.gridLayout_3.addWidget(self.comboBoxObservation2, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.obs2GroupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        DiagnosticDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DiagnosticDockWidget)
        QtCore.QMetaObject.connectSlotsByName(DiagnosticDockWidget)

    def retranslateUi(self, DiagnosticDockWidget):
        DiagnosticDockWidget.setWindowTitle(_translate("DiagnosticDockWidget", "Diagnostics", None))
        self.diagsGroupBox.setTitle(_translate("DiagnosticDockWidget", "Diagnostics", None))
        self.PackageLabel.setText(_translate("DiagnosticDockWidget", "Package:", None))
        self.variablesGroupBox.setTitle(_translate("DiagnosticDockWidget", "Variable", None))
        self.VarOptionsLabel_2.setText(_translate("DiagnosticDockWidget", "Variables:", None))
        self.RegionLabel_2.setText(_translate("DiagnosticDockWidget", "Seasons:", None))
        self.VarOptionsLabel.setText(_translate("DiagnosticDockWidget", "Variable Options:", None))
        self.RegionLabel.setText(_translate("DiagnosticDockWidget", "Region:", None))
        self.DS1checkBox.setText(_translate("DiagnosticDockWidget", "Use Dataset 1", None))
        self.DS1FilterLabel.setText(_translate("DiagnosticDockWidget", "File Filter:", None))
        self.pickDS1Path.setText(_translate("DiagnosticDockWidget", "Set Path", None))
        self.DS1PathLabel.setText(_translate("DiagnosticDockWidget", "DS1 Path", None))
        self.DS2checkBox.setText(_translate("DiagnosticDockWidget", "Use Dataset 2", None))
        self.pickDS2Path.setText(_translate("DiagnosticDockWidget", "Set Path", None))
        self.DS2FilterLabel.setText(_translate("DiagnosticDockWidget", "File Filter:", None))
        self.DS2PathLabel.setText(_translate("DiagnosticDockWidget", "DS2 Path", None))
        self.Obs1checkBox.setText(_translate("DiagnosticDockWidget", "Use Observations 1", None))
        self.pickObs1Path.setText(_translate("DiagnosticDockWidget", "Set Path", None))
        self.obs1PathLabel.setText(_translate("DiagnosticDockWidget", "ObsPath1", None))
        self.Obs1Label.setText(_translate("DiagnosticDockWidget", "Obs set 1:     ", None))
        self.Obs2checkBox.setText(_translate("DiagnosticDockWidget", "Use Observations 2", None))
        self.pickObs2Path.setText(_translate("DiagnosticDockWidget", "Set Path", None))
        self.obs2PathLabel.setText(_translate("DiagnosticDockWidget", "ObsPath2", None))
        self.label.setText(_translate("DiagnosticDockWidget", "Obs set 2:", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DiagnosticDockWidget = QtGui.QDockWidget()
    ui = Ui_DiagnosticDockWidget()
    ui.setupUi(DiagnosticDockWidget)
    DiagnosticDockWidget.show()
    sys.exit(app.exec_())

