# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Aug 29 19:00:15 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(978, 936)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabwidget = QtGui.QTabWidget(self.centralwidget)
        self.tabwidget.setDocumentMode(True)
        self.tabwidget.setObjectName(_fromUtf8("tabwidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab1)
        self.verticalLayout_4.setMargin(5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.frame = QtGui.QFrame(self.tab1)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.lblVar = QtGui.QLabel(self.frame)
        self.lblVar.setObjectName(_fromUtf8("lblVar"))
        self.horizontalLayout.addWidget(self.lblVar)
        self.tbVarInfo = QtGui.QToolButton(self.frame)
        self.tbVarInfo.setAutoFillBackground(True)
        self.tbVarInfo.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbVarInfo.setIcon(icon)
        self.tbVarInfo.setIconSize(QtCore.QSize(22, 22))
        self.tbVarInfo.setObjectName(_fromUtf8("tbVarInfo"))
        self.horizontalLayout.addWidget(self.tbVarInfo)
        self.tbVarDelete = QtGui.QToolButton(self.frame)
        self.tbVarDelete.setAutoFillBackground(True)
        self.tbVarDelete.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbVarDelete.setIcon(icon1)
        self.tbVarDelete.setIconSize(QtCore.QSize(22, 22))
        self.tbVarDelete.setObjectName(_fromUtf8("tbVarDelete"))
        self.horizontalLayout.addWidget(self.tbVarDelete)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lblPlot = QtGui.QLabel(self.frame)
        self.lblPlot.setObjectName(_fromUtf8("lblPlot"))
        self.horizontalLayout_2.addWidget(self.lblPlot)
        self.tbPlotInfo = QtGui.QToolButton(self.frame)
        self.tbPlotInfo.setAutoFillBackground(True)
        self.tbPlotInfo.setText(_fromUtf8(""))
        self.tbPlotInfo.setIcon(icon)
        self.tbPlotInfo.setIconSize(QtCore.QSize(22, 22))
        self.tbPlotInfo.setObjectName(_fromUtf8("tbPlotInfo"))
        self.horizontalLayout_2.addWidget(self.tbPlotInfo)
        self.tbPlotDelete = QtGui.QToolButton(self.frame)
        self.tbPlotDelete.setAutoFillBackground(True)
        self.tbPlotDelete.setText(_fromUtf8(""))
        self.tbPlotDelete.setIcon(icon1)
        self.tbPlotDelete.setIconSize(QtCore.QSize(22, 22))
        self.tbPlotDelete.setObjectName(_fromUtf8("tbPlotDelete"))
        self.horizontalLayout_2.addWidget(self.tbPlotDelete)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.label_6 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(100, 100))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/resources/images/clt_isofill.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.verticalLayout_4.addWidget(self.frame)
        self.tabwidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab2)
        self.verticalLayout.setMargin(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_2 = QtGui.QFrame(self.tab2)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lblVar_2 = QtGui.QLabel(self.frame_2)
        self.lblVar_2.setText(_fromUtf8(""))
        self.lblVar_2.setObjectName(_fromUtf8("lblVar_2"))
        self.horizontalLayout_3.addWidget(self.lblVar_2)
        self.tbVarInfo_2 = QtGui.QToolButton(self.frame_2)
        self.tbVarInfo_2.setAutoFillBackground(True)
        self.tbVarInfo_2.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/edit_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbVarInfo_2.setIcon(icon2)
        self.tbVarInfo_2.setIconSize(QtCore.QSize(22, 22))
        self.tbVarInfo_2.setObjectName(_fromUtf8("tbVarInfo_2"))
        self.horizontalLayout_3.addWidget(self.tbVarInfo_2)
        self.tbVarDelete_2 = QtGui.QToolButton(self.frame_2)
        self.tbVarDelete_2.setEnabled(False)
        self.tbVarDelete_2.setAutoFillBackground(True)
        self.tbVarDelete_2.setText(_fromUtf8(""))
        self.tbVarDelete_2.setIcon(icon1)
        self.tbVarDelete_2.setIconSize(QtCore.QSize(22, 22))
        self.tbVarDelete_2.setObjectName(_fromUtf8("tbVarDelete_2"))
        self.horizontalLayout_3.addWidget(self.tbVarDelete_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lblPlot_2 = QtGui.QLabel(self.frame_2)
        self.lblPlot_2.setText(_fromUtf8(""))
        self.lblPlot_2.setObjectName(_fromUtf8("lblPlot_2"))
        self.horizontalLayout_4.addWidget(self.lblPlot_2)
        self.tbPlotInfo_2 = QtGui.QToolButton(self.frame_2)
        self.tbPlotInfo_2.setAutoFillBackground(True)
        self.tbPlotInfo_2.setText(_fromUtf8(""))
        self.tbPlotInfo_2.setIcon(icon2)
        self.tbPlotInfo_2.setIconSize(QtCore.QSize(22, 22))
        self.tbPlotInfo_2.setObjectName(_fromUtf8("tbPlotInfo_2"))
        self.horizontalLayout_4.addWidget(self.tbPlotInfo_2)
        self.tbPlotDelete_2 = QtGui.QToolButton(self.frame_2)
        self.tbPlotDelete_2.setEnabled(False)
        self.tbPlotDelete_2.setAutoFillBackground(True)
        self.tbPlotDelete_2.setText(_fromUtf8(""))
        self.tbPlotDelete_2.setIcon(icon1)
        self.tbPlotDelete_2.setIconSize(QtCore.QSize(22, 22))
        self.tbPlotDelete_2.setObjectName(_fromUtf8("tbPlotDelete_2"))
        self.horizontalLayout_4.addWidget(self.tbPlotDelete_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.frame_2)
        self.label = QtGui.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        spacerItem4 = QtGui.QSpacerItem(20, 747, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.tabwidget.addTab(self.tab2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabwidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 978, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuProject = QtGui.QMenu(self.menubar)
        self.menuProject.setObjectName(_fromUtf8("menuProject"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionPlot = QtGui.QAction(MainWindow)
        self.actionPlot.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/map-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlot.setIcon(icon3)
        self.actionPlot.setObjectName(_fromUtf8("actionPlot"))
        self.actionSource = QtGui.QAction(MainWindow)
        self.actionSource.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/source.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSource.setIcon(icon4)
        self.actionSource.setObjectName(_fromUtf8("actionSource"))
        self.actionWorkflow = QtGui.QAction(MainWindow)
        self.actionWorkflow.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/icons/pipeline.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWorkflow.setIcon(icon5)
        self.actionWorkflow.setObjectName(_fromUtf8("actionWorkflow"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "UV-CDAT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Variable:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblVar.setText(QtGui.QApplication.translate("MainWindow", "clt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Plot:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPlot.setText(QtGui.QApplication.translate("MainWindow", "Isofill", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab1), QtGui.QApplication.translate("MainWindow", "Cloudness Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Variable:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Plot:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Drag a Variable and a Plot Type to start or use the buttons above", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab2), QtGui.QApplication.translate("MainWindow", "Plot 2", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProject.setTitle(QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindow.setTitle(QtGui.QApplication.translate("MainWindow", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlot.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSource.setText(QtGui.QApplication.translate("MainWindow", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWorkflow.setText(QtGui.QApplication.translate("MainWindow", "Workflow", None, QtGui.QApplication.UnicodeUTF8))

import uvcdat_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

