# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pvFileDialog.ui'
#
# Created: Thu Jun  7 09:05:22 2012
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_pvFileDialog(object):
    def setupUi(self, pvFileDialog):
        pvFileDialog.setObjectName("pvFileDialog")
        pvFileDialog.resize(683, 402)
        self.gridLayout = QtGui.QGridLayout(pvFileDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.label_3 = QtGui.QLabel(pvFileDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.hboxlayout.addWidget(self.label_3)
        self.Parents = QtGui.QComboBox(pvFileDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Parents.sizePolicy().hasHeightForWidth())
        self.Parents.setSizePolicy(sizePolicy)
        self.Parents.setObjectName("Parents")
        self.hboxlayout.addWidget(self.Parents)
        self.NavigateBack = QtGui.QToolButton(pvFileDialog)
        self.NavigateBack.setText("")
        self.NavigateBack.setAutoRaise(True)
        self.NavigateBack.setObjectName("NavigateBack")
        self.hboxlayout.addWidget(self.NavigateBack)
        self.NavigateForward = QtGui.QToolButton(pvFileDialog)
        self.NavigateForward.setText("")
        self.NavigateForward.setAutoRaise(True)
        self.NavigateForward.setObjectName("NavigateForward")
        self.hboxlayout.addWidget(self.NavigateForward)
        self.NavigateUp = QtGui.QToolButton(pvFileDialog)
        self.NavigateUp.setText("")
        self.NavigateUp.setAutoRaise(True)
        self.NavigateUp.setObjectName("NavigateUp")
        self.hboxlayout.addWidget(self.NavigateUp)
        self.CreateFolder = QtGui.QToolButton(pvFileDialog)
        self.CreateFolder.setText("")
        self.CreateFolder.setAutoRaise(True)
        self.CreateFolder.setObjectName("CreateFolder")
        self.hboxlayout.addWidget(self.CreateFolder)
        self.gridLayout.addLayout(self.hboxlayout, 0, 0, 1, 1)
        self.mainSplitter = QtGui.QSplitter(pvFileDialog)
        self.mainSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.mainSplitter.setObjectName("mainSplitter")
        self.splitter = QtGui.QSplitter(self.mainSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.mainSplitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Files = QtGui.QTreeView(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Files.sizePolicy().hasHeightForWidth())
        self.Files.setSizePolicy(sizePolicy)
        self.Files.setObjectName("Files")
        self.verticalLayout.addWidget(self.Files)
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.FileName = QtGui.QLineEdit(self.layoutWidget)
        self.FileName.setObjectName("FileName")
        self.gridlayout.addWidget(self.FileName, 0, 1, 1, 1)
        self.OK = QtGui.QPushButton(self.layoutWidget)
        self.OK.setObjectName("OK")
        self.gridlayout.addWidget(self.OK, 0, 2, 1, 1)
        self.Cancel = QtGui.QPushButton(self.layoutWidget)
        self.Cancel.setObjectName("Cancel")
        self.gridlayout.addWidget(self.Cancel, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridlayout)
        self.gridLayout.addWidget(self.mainSplitter, 1, 0, 1, 1)

        self.retranslateUi(pvFileDialog)
        QtCore.QObject.connect(self.OK, QtCore.SIGNAL("clicked()"), pvFileDialog.accept)
        QtCore.QObject.connect(self.Cancel, QtCore.SIGNAL("clicked()"), pvFileDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(pvFileDialog)
        pvFileDialog.setTabOrder(self.FileName, self.OK)
        pvFileDialog.setTabOrder(self.OK, self.Cancel)
        pvFileDialog.setTabOrder(self.Cancel, self.Parents)
        pvFileDialog.setTabOrder(self.Parents, self.NavigateBack)
        pvFileDialog.setTabOrder(self.NavigateBack, self.NavigateForward)
        pvFileDialog.setTabOrder(self.NavigateForward, self.NavigateUp)
        pvFileDialog.setTabOrder(self.NavigateUp, self.CreateFolder)
        pvFileDialog.setTabOrder(self.CreateFolder, self.Files)

    def retranslateUi(self, pvFileDialog):
        pvFileDialog.setWindowTitle(QtGui.QApplication.translate("pvFileDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("pvFileDialog", "Look in:", None, QtGui.QApplication.UnicodeUTF8))
        self.NavigateBack.setToolTip(QtGui.QApplication.translate("pvFileDialog", "Navigate Back", None, QtGui.QApplication.UnicodeUTF8))
        self.NavigateForward.setToolTip(QtGui.QApplication.translate("pvFileDialog", "Navigate Forward", None, QtGui.QApplication.UnicodeUTF8))
        self.NavigateUp.setToolTip(QtGui.QApplication.translate("pvFileDialog", "Navigate Up", None, QtGui.QApplication.UnicodeUTF8))
        self.CreateFolder.setToolTip(QtGui.QApplication.translate("pvFileDialog", "Create New Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("pvFileDialog", "File name:", None, QtGui.QApplication.UnicodeUTF8))
        self.OK.setText(QtGui.QApplication.translate("pvFileDialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.Cancel.setText(QtGui.QApplication.translate("pvFileDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

